print("Uploading")
shell.execute("wget",'https://raw.githubusercontent.com/BouncyRocket/-/%E2%80%8B%E2%80%8B/startup.lua','startup.lua')
print("Startup Uploaded")
shell.execute("wget",'https://raw.githubusercontent.com/BouncyRocket/-/%E2%80%8B%E2%80%8B/index.lua','index')
shell.execute("delete",'setup.lua')
shell.execute("clear")
os.reboot()
